name: Tests and Lint

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-versions: [ "3.13" ]

    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
    - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405
      with:
        python-version: ${{ matrix.python-versions }}

    - name: Install tox and coverage
      run: pip install tox tox-gh-actions

    - name: Run Python tests
      run: tox -r

    - name: Codecov
      uses: codecov/codecov-action@1af58845a975a7985b0beb0cbe6fbbb71a41dbad
      with:
        files: coverage.xml
        fail_ci_if_error: false
        verbose: true