name: Tests and Lint

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-versions: [ "3.13" ]

    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
    - uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97
      with:
        python-version: ${{ matrix.python-versions }}

    - name: Install tox and coverage
      run: pip install tox tox-gh-actions

    - name: Run Python tests
      run: tox -r

    - name: Codecov
      uses: codecov/codecov-action@0b35c9ecc4f0529d0eb674914510c22f85b196b4
      with:
        files: coverage.xml
        fail_ci_if_error: false
        verbose: true