name: FT pre-merge

on:
  pull_request_review:
    types: [submitted]

permissions:
  contents: read # Required: to checkout source code in the reusable functional-tests workflow
  actions: read  # Required: to access workflow run information and artifacts from other workflows

jobs:
  functional-tests-local:
    name: Deploy Local Services
    if: github.event.review.state == 'approved'
    uses: ./.github/workflows/functional-tests.yml
    with:
      worker_version: dev
      cli_version: dev
