name: FT pre-merge

on:
  pull_request_review:
    types: [submitted]

jobs:
  functional-tests-local:
    name: Deploy Local Services
    if: github.event.review.state == 'approved'
    uses: ./.github/workflows/functional-tests.yml
    with:
      worker_version: dev
      cli_version: dev
